// @ts-nocheck
/* eslint-disable */
// prettier-ignore
//
// AUTO-GENERATED by `cargo test -p uc-tauri --test specta_export`. DO NOT EDIT.
//
// 任何 #[tauri::command] / DTO / error enum 的形状变更都要重新跑这个测试
// 同步该文件，否则 CI 的 schema drift check 会拒绝合并。
//
// 用户/校验类错误的 code 集合。前端中央 IPC 封装层据此判断某个 command
// 拒绝是否属于「用户操作错误」—— 是则不上报 Sentry(正常产品流程),
// 否则按系统错误上报。未列出的 code 默认按系统错误处理(fail-safe)。
//
// 权威来源:`src-tauri/crates/uc-tauri/src/commands/severity.rs`。

export const USER_FACING_ERROR_CODES: ReadonlySet<string> = new Set([
  "Cancelled",
  "Conflict",
  "DEVICE_NOT_FOUND",
  "ENTRY_NOT_FOUND",
  "ENTRY_NOT_RESENDABLE",
  "INVALID_LAN_PARAMETER",
  "LABEL_EMPTY",
  "LABEL_TOO_LONG",
  "LAN_LISTENER_DISABLED",
  "NO_ELIGIBLE_TARGETS",
  "NotFound",
  "PASSWORD_TOO_LONG",
  "PASSWORD_TOO_SHORT",
  "SETUP_NOT_COMPLETED",
  "SPACE_NOT_INITIALIZED",
  "TARGET_NOT_TRUSTED",
  "USERNAME_CONTAINS_FORBIDDEN_CHARS",
  "USERNAME_MUST_START_WITH_LETTER",
  "USERNAME_TAKEN",
  "USERNAME_TOO_LONG",
  "USERNAME_TOO_SHORT",
  "ValidationError",
  "WRONG_PASSPHRASE",
]);
