// @ts-nocheck
/* eslint-disable */
// prettier-ignore
//
// AUTO-GENERATED by `cargo test -p uc-tauri --test specta_export`. DO NOT EDIT.
//
// 任何 #[tauri::command] / DTO / error enum 的形状变更都要重新跑这个测试
// 同步该文件，否则 CI 的 schema drift check 会拒绝合并。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Update tray menu labels to match the UI language.
	 * 
	 *  This is a UI sync command only; it does not persist settings.
	 */
	setTrayLanguage: (language: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_tray_language", { language, trace })),
	/**
	 *  Get the OS process ID of the Tauri application.
	 * 
	 *  获取 Tauri 应用的操作系统进程 ID。
	 */
	getTauriPid: () => __TAURI_INVOKE<number>("get_tauri_pid"),
	/**  Get the stable local device identifier used for telemetry correlation. */
	getDeviceId: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<string, CommandError>(__TAURI_INVOKE("get_device_id", { trace })),
	/**
	 *  Returns the full device + app meta to the webview.
	 * 
	 *  该命令是 PR1 跨设备可观测性改造的一部分:webview 启动后通过它一次性把
	 *  Sentry initialScope 补齐,让前后端事件在 Sentry 上能用同一组 tag(尤其是
	 *  `device.id`)互相关联。底层数据来自启动期一次性 resolve 的 [`uc_observability::ScopeContext`]。
	 */
	getDeviceMeta: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<DeviceMeta, CommandError>(__TAURI_INVOKE("get_device_meta", { trace })),
	/**
	 *  Read the daemon connection info from managed state.
	 * 
	 *  Pure status read from managed state; no usecase orchestration is required.
	 */
	getDaemonConnectionInfo: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	baseUrl: string,
	wsUrl: string,
} | null, CommandError>(__TAURI_INVOKE("get_daemon_connection_info", { trace })),
	/**
	 *  Exchange daemon bearer credentials for a short-lived webview session.
	 *
	 *  The raw bearer token stays in the native Tauri side; the webview only receives
	 *  the daemon's session JWT and its refresh metadata.
	 */
	getDaemonSession: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	sessionToken: string,
	expiresInSecs: number,
	refreshAtSecs: number,
} | null, CommandError>(__TAURI_INVOKE("get_daemon_session", { trace })),
	/**
	 *  Restarts the running Tauri application to apply settings changes.
	 * 
	 *  流程:
	 *  1. emit `app://shutting-down` → 前端 disconnect WebSocket
	 *  2. wait `SHUTDOWN_FRONTEND_GRACE_MS` 让 WS close frame 飞过 loopback
	 *  3. graceful shutdown owned daemon (释放 HTTP / LAN 端口),最长
	 *     [`DAEMON_SHUTDOWN_TIMEOUT`] 兜底
	 *  4. `app.restart()` —— Tauri spawn 新进程 + exit 当前进程
	 * 
	 *  不走 Tauri 的 `RunEvent::ExitRequested` 路径 —— `app.restart()` 是 raw
	 *  exit,不触发 RunEvent。所以这里**必须**自己重做一次 graceful shutdown,
	 *  否则新进程启动时旧 daemon 还在持端口 → bind 失败 → daemon 起不来。
	 * 
	 *  用户的"需要重启"设置(LAN-only Mode / mobile_sync 端口等)都走这条
	 *  路径。iroh `IrohNodeBuilder::bind` 是进程级单次约束(Pitfall 3),
	 *  任何涉及 iroh_config 变更的 settings 必须新进程重新 bind,所以
	 *  `app.restart()` 是合适的、唯一的入口。
	 */
	restartApp: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("restart_app", { trace })),
	/**
	 *  Update the "launch at login" preference and apply it to the OS.
	 * 
	 *  Persists `auto_start` through the settings facade first (the stored
	 *  preference is the source of truth), then reconciles the OS-level launch
	 *  registration via [`AutostartPort`]. If the OS step fails, the persisted
	 *  setting is rolled back so settings never claim a state the OS rejected.
	 * 
	 *  更新开机自启动偏好并应用到操作系统：先经设置 facade 持久化（存储偏好为
	 *  真相源），再通过 [`AutostartPort`] 对齐 OS 启动项；OS 步骤失败时回滚已
	 *  持久化的设置，避免设置声称一个 OS 未能达成的状态。
	 */
	updateAutostart: (enabled: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_autostart", { enabled, trace })),
	/**
	 *  Tauri command — thin shell over [`do_check_for_update`] that emits
	 *  `update_check_performed { source: "manual", ... }` after the inner
	 *  resolves. scheduler-driven checks emit the same event with a different
	 *  `source`（schema doc §7.8）；inner 函数本身不 emit。
	 */
	checkForUpdate: (channel: string | null, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	version: string,
	currentVersion: string,
	body: string | null,
	date: string | null,
} | null, string>(__TAURI_INVOKE("check_for_update", { channel, trace })),
	/**
	 *  Download the pending update in the background, broadcasting progress
	 *  via `UPDATE_PROGRESS_EVENT`. Awaitable: the future resolves when the
	 *  download completes, fails, or is cancelled.
	 * 
	 *  Thin shell over [`do_download_update`] that emits
	 *  `update_action_invoked { action = "download_bg", outcome = started }`
	 *  at entry (once the action actually transitions to `Downloading`) and
	 *  a terminal `Succeeded` / `Failed` / `Cancelled` after the inner
	 *  returns. Precondition rejections are returned to the frontend without
	 *  emitting any telemetry —— the user did not actually start a download,
	 *  so we keep the funnel分母干净.
	 * 
	 *  Pre-condition: state must be `Available`. `Downloading` returns
	 *  "already downloading"; `Ready` returns "already downloaded"; `None`
	 *  returns "no pending update".
	 */
	downloadUpdate: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("download_update", { trace })),
	/**
	 *  Signal an in-flight `download_update` to abort. No-op if the state is
	 *  not `Downloading`. The download future is dropped by the `tokio::select!`
	 *  in `download_update`, which terminates the underlying HTTP stream.
	 */
	cancelDownload: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { trace })),
	/**
	 *  Return the current download state so a freshly-mounted frontend listener
	 *  can sync up before attaching to `UPDATE_PROGRESS_EVENT`.
	 */
	getDownloadProgress: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<DownloadProgressSnapshot, string>(__TAURI_INVOKE("get_download_progress", { trace })),
	/**
	 *  Install the pending update.
	 * 
	 *  - `Ready`: install cached bytes via `Update::install`, then restart.
	 *    On failure, restore the `Ready` state so the user can retry.
	 *  - `Available`: legacy combined download+install path via
	 *    `Update::download_and_install`, with progress on the per-invocation
	 *    `Channel<DownloadEvent>` for compatibility with the existing dialog.
	 *  - `Downloading`: refuse (caller should wait or cancel first).
	 *  - `None`: refuse.
	 */
	installUpdate: (onEvent: Channel<DownloadEvent>, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("install_update", { onEvent, trace })),
	/**
	 *  Detect how the current binary was installed.
	 * 
	 *  Cached after the first call. On Linux the detection asks dpkg/rpm whether
	 *  `current_exe()` is in their package DB — that way users on a mixed system
	 *  (e.g. apt + rpm side-by-side) get the right answer rather than a guess
	 *  based on `/etc/*-release`.
	 */
	getInstallKind: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<InstallKind, string>(__TAURI_INVOKE("get_install_kind", { trace })),
	/**
	 *  Dev-only: manually open the Sparkle-style updater window with mock data.
	 * 
	 *  Wired to a debug-build button in `AboutSection.tsx` so we can iterate on
	 *  the window's UI without waiting for a real update to be detected. Release
	 *  builds short-circuit with an error so the command can't be misused —
	 *  `#[cfg]` is intentionally on the body, not the signature, to keep the
	 *  specta-generated TS surface stable across build profiles.
	 */
	devOpenUpdaterWindow: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("dev_open_updater_window", { trace })),
	/**
	 *  把前端 UI 触发的 update lifecycle 事件回送到后端 PostHog facade。
	 * 
	 *  仅 `DialogOpened` 会触发 `install_kind` probe；其他 variant 走直通映射。
	 *  `analytics::capture` 自身是 fire-and-forget，所以本 command 不返回 wire 错误
	 *  （即使 sink 在异步路径上失败，前端也无可处置；同 `commands/updater.rs`
	 *  内部 emission 一致）。
	 */
	captureUpdateUiEvent: (event: UpdateUiEvent_Deserialize, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("capture_update_ui_event", { event, trace })),
	/**
	 *  Open the application data directory in the system file manager.
	 *  在系统文件管理器中打开应用数据目录。
	 */
	openDataDirectory: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("open_data_directory", { trace })),
	/**
	 *  Open the application logs directory in the system file manager.
	 *  在系统文件管理器中打开应用日志目录。
	 */
	openLogsDirectory: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("open_logs_directory", { trace })),
	/**
	 *  拉一条 entry 的同步状态视图。
	 * 
	 *  前端 detail 面板在 entry 切换时调用,失败时(facade 未装配 / DB 故障)
	 *  返回 `InternalError`;entry 不存在返回 `NotFound`,前端据此降级渲染。
	 */
	clipboardEntryDeliveryView: (entryId: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<EntryDeliveryViewDto, CommandError>(__TAURI_INVOKE("clipboard_entry_delivery_view", { entryId, trace })),
	/**
	 *  用户主动 resend 一条本机 entry。命令走 in-process facade
	 *  (`AppFacade::resend_entry` → `ClipboardOutboundFacade::resend_entry`),
	 *  与 `clipboard_entry_delivery_view` 一致;不经 HTTP/webserver。
	 * 
	 *  入参:
	 *  - `entryId` —— 要重发的 entry id (字符串形态);
	 *  - `targetDeviceIds` —— `None` 派生差集,`Some(list)` 显式 fan-out;
	 *    `Some(vec![])` 与差集为空等价,返回 `NO_ELIGIBLE_TARGETS`。
	 * 
	 *  返回 `ResendEntryReportDto` (各 bucket 计数);失败返回 typed
	 *  `ResendEntryCommandError`,前端按 `code` 字段做 i18n。详细错误语义见
	 *  [`ResendEntryError`](uc_application::facade::ResendEntryError)。
	 */
	clipboardResendEntry: (args: ResendEntryArgs, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<ResendEntryReportDto, ResendEntryCommandError>(__TAURI_INVOKE("clipboard_resend_entry", { args, trace })),
	/**
	 *  取消一次进行中的入站文件传输。
	 * 
	 *  幂等:`transfer_id` 不在 inflight registry 时(没有进行中的 fetch /
	 *  已经被取消过)正常返回。本命令完成后前端会通过 `file-transfer.status_changed`
	 *  host event 收到 cancelled 状态。
	 */
	cancelFileTransfer: (transferId: string, reason: CancelTransferReasonDto, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_file_transfer", { transferId, reason, trace })),
	/**
	 *  Hide the quick panel, re-activate the previous app, and paste.
	 * 
	 *  隐藏快捷面板，重新激活之前的应用，并粘贴。
	 */
	pasteToPreviousApp: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("paste_to_previous_app", { trace })),
	/**
	 *  Dismiss the quick panel and return focus to the previous app (no paste).
	 * 
	 *  关闭快捷面板并将焦点返回到之前的应用（不粘贴）。
	 */
	dismissQuickPanel: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("dismiss_quick_panel", { trace })),
	/**  Update quick panel size and centered position from the active UI scale. */
	setQuickPanelLayout: (scale: number | null, previewExpanded: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_quick_panel_layout", { scale, previewExpanded, trace })),
	/**
	 *  Finalize the quick panel show after the frontend has cleared stale state.
	 * 
	 *  前端清理完旧状态后，实际显示快捷面板窗口。
	 */
	finalizeQuickPanelShow: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("finalize_quick_panel_show", { trace })),
	/**
	 *  实时启用/禁用快捷面板。
	 * 
	 *  与 `update_keyboard_shortcuts` 走同一把 [`KeyboardShortcutsUpdateLock`],
	 *  因为两者都会改 OS 全局快捷键的注册状态——并发执行会让 OS 状态、
	 *  [`CurrentShortcuts`] 内存视图、和 facade 持久化值互相错位。
	 * 
	 *  流程:
	 *    1. 拿锁,读当前 settings。
	 *    2. 与 `enabled` 比较:无变化直接返回。
	 *    3. 计算 desired OS 快捷键列表(开启时 = `resolve_quick_panel_shortcuts`,
	 *       关闭时 = `[]`)。
	 *    4. 在 main thread 上一次性完成:开启 → `pre_create` + `register`,
	 *       关闭 → 只 `unregister`,**不**销毁面板窗口。`tauri-plugin-global-shortcut`
	 *       与 webview 创建都要求 main thread。
	 *    5. 调 facade 持久化 patch。失败时反向回滚 OS 副作用,避免出现
	 *       "OS 已生效但磁盘没存"或反过来的撕裂状态。
	 *    6. 成功后 `shortcut_registry.replace(...)`,让后续 `update_keyboard_shortcuts`
	 *       能算对 old/new diff。
	 * 
	 *  **关闭路径不彻底释放 webview**:macOS 上销毁 NSPanel 会与 ObjC 类替换 +
	 *  on_window_event 异步任务发生 race 而崩溃。所以关闭只反注册 OS 快捷键,
	 *  隐藏的 WKWebView / WebContent XPC 进程依旧存在,UI 会提示用户重启 GUI
	 *  才能完全释放资源。下次启动期 `quick_panel.enabled = false` 会跳过
	 *  `pre_create`,自然不会再有这些进程。
	 */
	setQuickPanelEnabled: (enabled: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_quick_panel_enabled", { enabled, trace })),
	/**  保存键盘快捷键，并同步快捷面板全局快捷键的 OS 注册状态。 */
	updateKeyboardShortcuts: (shortcuts: { [key in string]: ShortcutKeyDto | null }, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<UpdateKeyboardShortcutsResult, CommandError>(__TAURI_INVOKE("update_keyboard_shortcuts", { shortcuts, trace })),
	/**
	 *  对单个候选中继 URL 发起一次握手探测。
	 * 
	 *  不读取也不修改任何持久化设置;UI 可以重复调用以做"在保存前先试一下"。
	 *  探测失败映射到 [`RelayProbeOutcome`] 的细分变体,系统级故障(adapter
	 *  未装配等)走 [`CommandError`]。
	 */
	probeRelayUrl: (url: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<RelayProbeOutcome, CommandError>(__TAURI_INVOKE("probe_relay_url", { url, trace })),
	/**
	 *  登记一台 iPhone Shortcut 设备：颁发 (username, password) Basic Auth 凭据 +
	 *  渲染 SyncClipboard install URL 的二维码。`password` 在返回值里是**唯一一次**
	 *  面向用户的明文回显——前端必须立即展示 + 强制用户勾选"已保存"才允许关闭。
	 */
	registerMobileDevice: (args: RegisterMobileDeviceArgs, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<RegisterMobileDeviceResult, MobileSyncError>(__TAURI_INVOKE("register_mobile_device", { args, trace })),
	/**
	 *  撤销一台已登记设备。`Ok(())` 表示成功；`DeviceNotFound` 表示设备已不在
	 *  仓储里（UI 列表过期），前端据此提示刷新。
	 */
	revokeMobileDevice: (deviceId: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, MobileSyncError>(__TAURI_INVOKE("revoke_mobile_device", { deviceId, trace })),
	/**
	 *  列出已登记设备。结果按"最近活跃 desc → 创建时间 desc"排序。不含
	 *  password_hash；username 作为辅助识别字段透传给前端。
	 */
	listMobileDevices: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<MobileDeviceView[], MobileSyncError>(__TAURI_INVOKE("list_mobile_devices", { trace })),
	/**
	 *  给一台已登记设备换一份新密码。`password = None`(字段缺失 / null)走
	 *  minter 自动颁发;给值则按 8–256 字符校验。返回值 `password` 是**唯一一次**
	 *  明文回显 —— 之后只以 PHC 存在,UI 必须立即展示并告知用户同步更新 iPhone
	 *  shortcut 里的 password 字段(旧密码已立即失效)。
	 */
	rotateMobilePassword: (args: RotateMobilePasswordArgs, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<RotateMobilePasswordResult, MobileSyncError>(__TAURI_INVOKE("rotate_mobile_password", { args, trace })),
	/**  读移动端同步设置 + 当前 LAN URL + 可用 install methods 的合成视图。 */
	getMobileSyncSettings: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<MobileSyncSettingsViewDto, MobileSyncError>(__TAURI_INVOKE("get_mobile_sync_settings", { trace })),
	/**
	 *  更新移动端同步设置。GUI daemon 装配下 LAN listener 由
	 *  `MobileLanLifecyclePort` 即时切换,无需重启;`restart_required` 字段
	 *  的具体语义见 [`UpdateMobileSyncSettingsResult::restart_required`] 文档。
	 */
	updateMobileSyncSettings: (args: UpdateMobileSyncSettingsArgs_Deserialize, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<UpdateMobileSyncSettingsResult, MobileSyncError>(__TAURI_INVOKE("update_mobile_sync_settings", { args, trace })),
	/**
	 *  列出可作为二维码 URL 候选的本机 IPv4 LAN 接口。仅返回 RFC1918 私有地址，
	 *  按 10/8 → 172.16/12 → 192.168/16 排序。
	 */
	listMobileLanInterfaces: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<LanInterfaceView[], MobileSyncError>(__TAURI_INVOKE("list_mobile_lan_interfaces", { trace })),
	/**
	 *  用户主动输入口令解锁(in-process)。
	 * 
	 *  调用链:Tauri command → `runtime.app_facade().space_setup` →
	 *  `SpaceSetupFacade::unlock_space(input)` →
	 *  `UnlockSpaceUseCase` → `SpaceAccessPort::unlock(space_id, passphrase)`。
	 *  全程同进程,`passphrase` 不进任何 socket。
	 * 
	 *  成功后 `InMemorySession::set_master_key` 已写入,session 立即 ready;
	 *  前端继续调 `POST /lifecycle/ready` 触发 daemon deferred services
	 *  (clipboard watcher / sync 等)启动。
	 */
	unlockSpaceWithPassphrase: (args: UnlockSpaceArgs, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<UnlockSpaceResultDto, UnlockSpaceCommandError>(__TAURI_INVOKE("unlock_space_with_passphrase", { args, trace })),
	/**
	 *  In-process 等价于历史 HTTP `POST /encryption/unlock`(silent keyring
	 *  resume,不接受 passphrase)。**这是替换 `DaemonQueryClient::unlock_encryption()`
	 *  的 in-process 路径**——GUI 与 daemon 同进程,完全没必要再绕 HTTP。
	 * 
	 *  语义保持原 endpoint 一致: `Ok(true)` keyring 命中、`Ok(false)`
	 *  "nothing to resume"(空 profile / 还没 setup)、`Err` 异常 / 漂移。
	 */
	trySilentUnlock: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<TrySilentUnlockResult, TrySilentUnlockError>(__TAURI_INVOKE("try_silent_unlock", { trace })),
	/**
	 *  用户主动触发的"重置并重新开始"。
	 * 
	 *  调用链:Tauri command → `runtime.app_facade().space_setup` →
	 *  `SpaceSetupFacade::factory_reset()` →
	 *  `SpaceAccessPort::factory_reset` + `SetupStatusPort::set_status` +
	 *  `invitation_holder.cancel_all()`。全程同进程。
	 * 
	 *  不接收任何参数:`SpaceAccessAdapter` 用 `current_profile` 推 keyslot
	 *  范围,facade 内部 mint 一个新的 `SpaceId` 作为 opaque handle。前端
	 *  应在调用本 command **前** 通过二次确认对话框收集用户的明确意图。
	 */
	factoryResetSpace: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<FactoryResetResult, FactoryResetCommandError>(__TAURI_INVOKE("factory_reset_space", { trace })),
	/**
	 *  调整 macOS 主窗口三色交通灯（close/min/zoom）按钮位置。
	 * 
	 *  `offset_x` / `offset_y` 相对系统给的标准位置偏移，**屏幕坐标系**：
	 *  正 X 向右、正 Y 向下。调用幂等。非 macOS 平台 no-op。
	 */
	setTrafficLightPosition: (offsetX: number | null, offsetY: number | null, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_traffic_light_position", { offsetX, offsetY, trace })),
};

/** Events */
export const events = {
	clipboardDeliveryStatusChanged: makeEvent<ClipboardDeliveryStatusChanged>("clipboard-delivery-status-changed"),
};

/* Types */
/**
 *  取消原因的前端可序列化镜像。与领域 `FileTransferCancellationReason`
 *  一一对应,但用 camelCase tag 让前端 union 写起来自然。
 * 
 *  当前 P1 只暴露 `LocalUser` —— 用户主动点取消按钮触发本命令。
 *  其它变体(`RemotePeer` / `Replaced` / `Unknown`)是 domain 内部状态
 *  转移,不通过本 IPC 入口。
 */
export type CancelTransferReasonDto = { tag: "localUser" };

/**
 *  `clipboard_delivery_status_changed` 事件 payload。
 * 
 *  前端 detail 视图按 `entry_id` 过滤后 refetch
 *  [`crate::commands::clipboard_delivery::EntryDeliveryViewDto`],
 *  拿 view 内的 status 渲染。`target_device_id` 当前未被消费,留作未来
 *  per-peer 局部刷新的钩子。
 */
export type ClipboardDeliveryStatusChanged = {
	/**
	 *  触发本次变更的 entry id。前端 detail 视图按当前打开的 entry_id 过滤,
	 *  只对匹配事件 refetch。
	 */
	entryId: string,
	/**  投递目标对端。view 渲染时按对端聚合状态,事件粒度也是按对端。 */
	targetDeviceId: string,
};

/**
 *  Typed command error taxonomy for Tauri command boundary.
 * 
 *  Serializes to {"code": "...", "message": "..."} for frontend discriminated union handling.
 */
export type CommandError = { code: "NotFound"; message: string } | { code: "InternalError"; message: string } | { code: "Timeout"; message: string } | { code: "Cancelled"; message: string } | { code: "ValidationError"; message: string } | { code: "Conflict"; message: string };

export type DaemonConnectionPayload = {
	baseUrl: string,
	wsUrl: string,
};

export type DaemonSessionPayload = {
	sessionToken: string,
	expiresInSecs: number,
	refreshAtSecs: number,
};

/**  失败原因。i18n key 命名约定:`delivery.failureReason.<variant 小驼峰>`。 */
export type DeliveryFailureReasonDto = "offline" | "localPolicy" | "peerRejected" | "io" | "internal";

/**
 *  暴露给 webview 的设备和应用元数据，用于补齐前端 Sentry scope。
 * 
 *  字段命名与后端 `ScopeContext` 一一对应（`device.id` / `device.role` /
 *  `device.platform` / `app.version` / `app.channel`）。webview 侧的
 *  `device.role` 默认仍是 `webview`，这里返回的 `device_role` 是 *Rust 主进程*
 *  的角色（`gui-host`），webview 把它打到 `device.host_role` 二级 tag 上,
 *  便于 Sentry 上同时看到两端。
 */
export type DeviceMeta = {
	deviceId: string,
	deviceRole: string,
	platform: string,
	appVersion: string,
	appChannel: string,
};

/**
 *  Events emitted during update download.
 * 
 *  Carried both via the broadcast `UPDATE_PROGRESS_EVENT` (background
 *  download) and via the per-invocation `Channel<DownloadEvent>` passed to
 *  `install_update` (legacy combined download+install path).
 */
export type DownloadEvent = { event: "Started"; data: {
	contentLength: number | null,
} } | { event: "Progress"; data: {
	chunkLength: number,
} } | { event: "Finished" } | { event: "Failed"; data: {
	error: string,
} };

/**
 *  Coarse-grained phase used by `get_download_progress` so a frontend that
 *  mounts mid-download can render the right icon variant.
 */
export type DownloadPhase = "idle" | "available" | "downloading" | "ready";

/**
 *  Snapshot of current download state, queryable from the frontend so a
 *  just-mounted listener can sync up before attaching to the event stream.
 */
export type DownloadProgressSnapshot = {
	phase: DownloadPhase,
	downloaded: number,
	total: number | null,
	/**  Newly-available (latest) version. `None` when phase is `Idle`. */
	version: string | null,
	/**
	 *  Currently-installed app version, lifted directly from
	 *  `app.package_info().version`. Always populated even when phase is
	 *  `Idle`, so a mid-mount frontend can render "current vs. latest"
	 *  without waiting for a fresh `check_for_update` round-trip.
	 */
	currentVersion: string,
	/**
	 *  Release notes for the available version, if any. `None` when phase
	 *  is `Idle` or the release ships no notes.
	 */
	body: string | null,
	/**
	 *  Release date for the available version, if any. `None` when phase
	 *  is `Idle`.
	 */
	date: string | null,
};

/**  状态枚举:`tag` + `reason` 形式,便于前端区分四档与失败子分类。 */
export type EntryDeliveryStatusDto = { tag: "pending" } | { tag: "delivered" } | { tag: "duplicate" } | { tag: "failed"; reason: DeliveryFailureReasonDto };

export type EntryDeliveryTargetDto = {
	targetDeviceId: string,
	/**
	 *  取自空间成员目录中的人类可读名;不命中时为 `null`,前端 fallback
	 *  到 `targetDeviceId` 截断。
	 */
	targetDeviceName: string | null,
	status: EntryDeliveryStatusDto,
	/**  失败时的 wire 层错误细节,供 UI tooltip / 详情展开使用。 */
	reasonDetail: string | null,
	/**
	 *  `Pending` 时为 `None`(从未尝试过)。`#[specta(type = ...)]` 告诉 specta
	 *  这是个 ms 精度的 epoch,实际值不会超过 JS Number 安全整数范围 (~285 万年),
	 *  用 `Number<i64>` 包装绕过 BigInt 禁用规则,与 mobile_sync.rs 的 `last_seen_at_ms`
	 *  同源。
	 */
	updatedAtMs: number | null,
};

/**
 *  `EntryDeliveryView` 的前端可序列化镜像。字段命名与领域模型保持一致,
 *  只在序列化时改写成 camelCase。
 */
export type EntryDeliveryViewDto = {
	entryId: string,
	source: EntrySourceDto,
	deliveries: EntryDeliveryTargetDto[],
};

/**  entry 来源描述。`tag` 字段供前端 discriminated union 直接 switch。 */
export type EntrySourceDto = 
/**  本机捕获。 */
{ tag: "local" } | 
/**
 *  远端推送。`deviceId` 是来源设备,`deviceName` 取自空间成员目录;
 *  不命中时为 `null`,前端 fallback 到 device_id 截断。
 */
{ tag: "remote"; deviceId: string; deviceName: string | null } | 
/**  追踪机制启用前已存在的老 entry,无可靠投递信息。 */
{ tag: "historical" };

/**
 *  前端可 `error.code` switch 的 typed 错误。序列化形态:
 *  `{"code": "KEY_MATERIAL_WIPE_FAILED", "message": "..."}` 等。
 */
export type FactoryResetCommandError = 
/**
 *  space_setup facade 尚未装配——bootstrap 还没跑完或装配失败。
 *  前端应延后重试或提示用户重启应用。
 */
{ code: "FACADE_UNAVAILABLE" } | 
/**
 *  keyslot / KEK 删除失败。前端应展示通用错误并保留 UnlockPage 状态
 *  (用户至少还能继续尝试输口令);不应跳回 SetupPage——因为残留的
 *  keyslot 会让随后的 init 立即撞 AlreadyInitialized。
 */
{ code: "KEY_MATERIAL_WIPE_FAILED"; message: string } | 
/**
 *  key material 已清但 setup_status 没清。UI 现在处于过渡态:keyslot
 *  已无、setup_status 仍说 completed。最稳的引导是让用户重启应用。
 */
{ code: "STORAGE_FAILED"; message: string } | 
/**  兜底:其他非预期失败。 */
{ code: "INTERNAL"; message: string };

/**
 *  重置成功后返回的占位元数据。当前无字段——保留为对象以便未来扩展
 *  (比如下一步推荐操作的提示),而不必改 wire 形状。
 */
export type FactoryResetResult = Record<string, never>;

/**
 *  Installation provenance of the running binary.
 * 
 *  Used by the frontend to short-circuit in-app update when the user is on a
 *  system-packaged Linux build: Tauri's Linux updater only supports
 *  AppImage, so deb/rpm users must be routed to their package manager.
 */
export type InstallKind = "macos" | "windows" | 
/**
 *  Windows portable ("green") zip. The in-app updater would try to run the
 *  NSIS installer, which installs into Program Files rather than updating
 *  the portable folder — so the frontend routes this kind to a
 *  "download the new portable zip" dialog instead of self-installing.
 */
"windowsportable" | "appimage" | "deb" | "rpm" | "unknown";

/**  `list_mobile_lan_interfaces` 单条结果。 */
export type LanInterfaceView = {
	name: string,
	ipv4: string,
};

/**
 *  `list_mobile_devices` 单条结果。来自 `MobileDeviceSummary`，不含
 *  password_hash；username 透传给前端作为辅助识别字段。
 */
export type MobileDeviceView = {
	deviceId: string,
	label: string,
	clientType: string,
	username: string,
	createdAtMs: number,
	lastSeenAtMs: number | null,
	lastSeenIp: string | null,
	reportedName: string | null,
	reportedOs: string | null,
};

/**
 *  前端直接 `error.code` switch 的 typed 错误。
 * 
 *  序列化形态：`{"code": "USERNAME_TAKEN", "username": "..."}`。
 *  不复用 `commands::error::CommandError`（那个用了 `tag = "code", content =
 *  "message"` 只能带单一字符串负载），mobile_sync 校验错误需要 `min` /
 *  `max` / `username` / `reason` 等结构化字段。
 */
export type MobileSyncError = { code: "FACADE_UNAVAILABLE" } | { code: "LABEL_EMPTY" } | { code: "LABEL_TOO_LONG"; max: number } | { code: "LAN_LISTENER_DISABLED" } | { code: "USERNAME_TAKEN"; username: string } | { code: "USERNAME_TOO_SHORT"; min: number; got: number } | { code: "USERNAME_TOO_LONG"; max: number; got: number } | { code: "USERNAME_MUST_START_WITH_LETTER" } | { code: "USERNAME_CONTAINS_FORBIDDEN_CHARS" } | { code: "PASSWORD_TOO_SHORT"; min: number } | { code: "PASSWORD_TOO_LONG"; max: number } | { code: "PASSWORD_HASH_FAILED"; message: string } | { code: "DEVICE_NOT_FOUND"; deviceId: string } | { code: "INVALID_LAN_PARAMETER"; reason: string } | { code: "SETTINGS_LOAD_FAILED"; message: string } | { code: "SETTINGS_SAVE_FAILED"; message: string } | { code: "ENDPOINT_INFO_FAILED"; message: string } | { code: "LAN_PROBE_FAILED"; message: string } | { code: "NO_LAN_INTERFACE_AVAILABLE" } | { code: "PERSISTENCE_FAILED"; message: string } | { code: "QR_RENDER_FAILED"; message: string };

/**  `get_mobile_sync_settings` 返回值。 */
export type MobileSyncSettingsViewDto = {
	enabled: boolean,
	lanListenEnabled: boolean,
	lanAdvertiseIp: string | null,
	lanPort: number | null,
	/**
	 *  daemon 端 LAN listener 的 bind 失败原因(端口占用 / IP 不存在 / 权限)。
	 *  `Some` 表示 daemon 真的尝试过 bind 但失败,前端据此显示具体错误。
	 *  监听 URL 不再透出 —— 前端从 `lanAdvertiseIp` + `lanPort` 自行拼接。
	 */
	lanListenerError: string | null,
	shortcutInstallMethods: ShortcutInstallMethodView[],
};

/**  不可重发的细分原因。i18n key 命名约定:`delivery.resend.error.notResendable.<variant>`。 */
export type NotResendableReasonDto = 
/**
 *  entry 来自远端 peer。视图层已对远端 entry 隐藏重发按钮;走到此处
 *  说明前端绕过视图直接调命令,或视图状态过期。
 */
"remoteOrigin" | 
/**
 *  本机已不持有 plaintext / 必要 blob (paste rep `Lost` / 文件被 GC /
 *  blob store 已清理)。前端提示用户该 entry 已无法重新发送。
 */
"payloadLost";

/**  `register_mobile_device` 入参。 */
export type RegisterMobileDeviceArgs = {
	label: string,
	/**  留空（缺字段或显式 null）走 minter 自动颁发；给值则按规则严格校验。 */
	username?: string | null,
	password?: string | null,
};

/**
 *  `register_mobile_device` 返回值。
 * 
 *  `password` 是**唯一一次**面向前端的明文回显——之后只以 PHC 形式存在于
 *  服务端 sqlite。前端拿到后必须立即在 modal 里展示 + 强制用户勾选"已保存"
 *  才让关闭。
 */
export type RegisterMobileDeviceResult = {
	deviceId: string,
	label: string,
	clientType: string,
	createdAtMs: number,
	baseUrl: string,
	username: string,
	password: string,
	/**
	 *  SyncClipboard "Clipboard EX" iCloud 共享链接(常量)。前端把它放在
	 *  "安装快捷指令"次要 tab 里, 不再作为 connect-URI tab 的主 QR 内容。
	 */
	installUrl: string,
	/**
	 *  `installUrl` 的二维码 PNG, Base64 编码后由前端 `<img src="data:...">`
	 *  直接渲染。让 iPhone 相机直接扫码安装快捷指令, 替代用户在桌面上
	 *  肉眼抄长长的 iCloud 链接到 Safari 的旧体验。与 `qrCodePngBase64`
	 *  (编 `connectUri`) 字节不同, 用途也不同 — 前者一次性安装, 后者
	 *  每次添加设备扫一次。
	 */
	installQrCodePngBase64: string,
	/**
	 *  `uniclipboard://connect?v=1&svc=mobile-sync&p=<base64url-json>`。
	 *  QR 主内容: iOS Shortcut 扫描后一次性解出 base_url / username /
	 *  password 直接填三栏, 替代旧版"用户肉眼抄写"。协议详见
	 *  `docs/architecture/mobile-sync-connect-uri.md`。
	 */
	connectUri: string,
	/**
	 *  Base64-encoded PNG bytes; 前端 `<img src="data:image/png;base64,...">`
	 *  直接渲染。当前编码的是 `connectUri`(阶段 2 起), 不再是 `installUrl`。
	 */
	qrCodePngBase64: string,
};

/**
 *  一次 `probe_relay_url` 调用的细分结果。
 * 
 *  探测失败属于"用户可以理解的预期场景"(URL 写错、对端 DNS 不可达、TLS
 *  不可信等),所以这些状态以 `Ok(outcome)` 的形式返回,让前端可以在不抛
 *  异常的前提下区分文案。系统级故障(facade 缺失装配、trace 解析失败等)
 *  仍然走 [`CommandError`]。
 */
export type RelayProbeOutcome = { kind: "success"; latencyMs: number } | { kind: "invalidUrl"; message: string } | { kind: "dns"; message: string } | { kind: "tls"; message: string } | { kind: "handshake"; message: string } | { kind: "timeout" } | { kind: "other"; message: string };

/**
 *  `clipboard_resend_entry` 入参。
 * 
 *  `targetDeviceIds`:
 *  - 字段缺失 / `null` → `None` → use case 派生 `trusted_peer \
 *    (Delivered ∪ Duplicate)` 差集；
 *  - `[]` → `Some(vec![])`，等价于零目标，use case 返回 `NoEligibleTargets`；
 *  - `["dev-a", "dev-b"]` → 仅向列出的设备重发，列表里的 device 必须在
 *    trusted_peer 列表内，否则返回 `TargetNotTrusted`。
 */
export type ResendEntryArgs = {
	entryId: string,
	targetDeviceIds?: string[] | null,
};

/**
 *  `clipboard_resend_entry` 失败时的 typed 错误。前端 `error.code` 即
 *  discriminator,各变体的额外字段对应 ADR §2.5.4 的失败语义。
 * 
 *  不复用 `CommandError`:`Conflict(String)` 只能塞一段文本,而本错误
 *  集合需要 `deviceId` / `reason` / `entryId` 等结构化字段供 i18n key
 *  选择与文案占位。参考 `mobile_sync::MobileSyncError` 同模式。
 */
export type ResendEntryCommandError = { code: "ENTRY_NOT_FOUND"; entryId: string } | { code: "ENTRY_NOT_RESENDABLE"; entryId: string; reason: NotResendableReasonDto } | { code: "TARGET_NOT_TRUSTED"; deviceId: string } | { code: "NO_ELIGIBLE_TARGETS" } | { code: "STORAGE"; message: string } | { code: "DISPATCH"; message: string };

/**
 *  `clipboard_resend_entry` 成功返回 —— fan-out 后的聚合计数。语义同
 *  [`ResendReport`](uc_application::facade::ResendReport)，camelCase 后给前端
 *  渲染 toast / detail badge。
 */
export type ResendEntryReportDto = {
	/**  已落 `Delivered` 投递记录的目标数。 */
	accepted: number,
	/**  对端确认为重复内容 (content_hash 已存在) 的目标数。 */
	duplicate: number,
	/**  对端不可达 (presence offline / dial 失败) 的目标数。 */
	offline: number,
	/**  其他错误 (peer rejected / IO / internal) 的目标数。 */
	errored: number,
	/**
	 *  fan-out deadline 内未 settle、被搬到后台继续 join 的目标数。
	 *  后台完成时会写 delivery record 并发 `ClipboardDeliveryStatusChanged`
	 *  事件,前端 detail badge 据此自动刷新。
	 */
	pending: number,
};

/**
 *  `rotate_mobile_password` 入参。`password = None` (字段缺失或 null) 走
 *  minter 自动颁发新明文;给值则按规则严格校验。
 */
export type RotateMobilePasswordArgs = {
	deviceId: string,
	password?: string | null,
};

/**
 *  `rotate_mobile_password` 返回值。`password` 是**唯一一次**面向用户的
 *  明文回显 —— 之后只以 PHC 形式存在。前端必须立即在 modal 里展示, 并
 *  提示用户同步更新 iPhone shortcut 里的 password 字段(旧密码已立即
 *  失效)。
 */
export type RotateMobilePasswordResult = {
	deviceId: string,
	username: string,
	password: string,
};

export type ShortcutInstallMethodView = {
	/**  `tokenInjected` / `icloudGeneric`（v1 仅前者可用）。 */
	method: string,
	available: boolean,
	disabledReason: string | null,
};

export type ShortcutKeyDto = string | string[];

export type TraceMetadata = {
	trace_id: string,
	timestamp: number,
};

export type TrySilentUnlockError = 
/**  app facade 尚未装配。 */
{ code: "FACADE_UNAVAILABLE" } | 
/**
 *  keyring 中 KEK 与磁盘 keyslot 漂移 / 损坏 / 其他非预期错误。
 *  前端应弹出 "Unlock space" modal 收集明文口令,走
 *  [`unlock_space_with_passphrase`] 兜底。
 */
{ code: "INTERNAL"; message: string };

export type TrySilentUnlockResult = {
	/**
	 *  `true` = keyring 命中 + unwrap 成功,session 已 ready;
	 *  `false` = "没什么可恢复的"(还没 setup / setup 完但 keyslot 缺失);
	 *  注意 keyring 与 keyslot **漂移**会走 `Err` 而不是 `Ok(false)`,
	 *  前端据此区分"该弹解锁 modal" vs "该走 init/join 引导"。
	 */
	resumed: boolean,
};

/**  见 [`analytics::DialogOpenSource`]。wire form: `notification` | `sidebar_icon`。 */
export type UiDialogOpenSource = "notification" | "sidebar_icon";

/**
 *  见 [`analytics::DismissSource`]。wire form: `dialog_later` | `dialog_closed` |
 *  `package_manager_dialog_closed`。
 */
export type UiDismissSource = "dialog_later" | "dialog_closed" | "package_manager_dialog_closed";

/**  见 [`analytics::UpdateAction`]。wire form: `download_bg` | `install`。 */
export type UiUpdateAction = "download_bg" | "install";

/**
 *  见 [`analytics::UpdateActionOutcome`]。wire form: `started` | `succeeded` |
 *  `failed` | `cancelled`。
 */
export type UiUpdateActionOutcome = "started" | "succeeded" | "failed" | "cancelled";

/**  见 [`analytics::UpdatePhase`]。wire form: `available` | `downloading` | `ready`。 */
export type UiUpdatePhase = "available" | "downloading" | "ready";

/**
 *  前端 modal 提交的解锁请求。
 * 
 *  `passphrase` 在 Tauri IPC 边界以明文存在,**绝不**应当再往 HTTP/TCP
 *  上序列化(那等于送到本机 socket 上,违反 §安全)——这一边界仅止于
 *  同进程内 invoke handler。
 */
export type UnlockSpaceArgs = {
	passphrase: string,
};

/**
 *  前端可 `error.code` switch 的 typed 错误。序列化形态:
 *  `{"code": "WRONG_PASSPHRASE"}` / `{"code": "INTERNAL", "message": "..."}`。
 */
export type UnlockSpaceCommandError = 
/**
 *  space_setup facade 尚未装配——bootstrap 还没跑完或装配失败。
 *  前端应延后重试或提示用户重启应用。
 */
{ code: "FACADE_UNAVAILABLE" } | 
/**  没有 setup 过——前端应引导走 init / join 流程,而不是 unlock。 */
{ code: "SETUP_NOT_COMPLETED" } | 
/**
 *  `setup_status.has_completed=true` 但磁盘 keyslot 缺失。
 *  前端应引导 factory reset。
 */
{ code: "SPACE_NOT_INITIALIZED" } | 
/**
 *  口令不能 unwrap 已存 master key。前端应在 modal 中提示
 *  "口令错误,请重试",**不关闭** modal。
 */
{ code: "WRONG_PASSPHRASE" } | 
/**
 *  keyslot 文件存在但版本不支持 / 反序列化失败。再正确的口令也
 *  派生不出能解开的 KEK。前端应引导 factory reset 或重新 join。
 */
{ code: "CORRUPTED_KEY_MATERIAL" } | 
/**
 *  兜底:IO / 序列化 / migration resume 等非预期失败。`message`
 *  仅面向开发者日志,前端展示通用错误对话框 + Sentry 上报即可。
 */
{ code: "INTERNAL"; message: string };

/**  解锁成功后返回的最小元数据。 */
export type UnlockSpaceResultDto = {
	spaceId: string,
};

export type UpdateKeyboardShortcutsResult = {
	keyboardShortcuts: { [key in string]: ShortcutKeyDto },
};

/**  Metadata returned to the frontend when an update is available. */
export type UpdateMetadata = {
	version: string,
	currentVersion: string,
	body: string | null,
	date: string | null,
};

/**
 *  `update_mobile_sync_settings` 入参 patch。
 * 
 *  `lanAdvertiseIp` / `lanPort` 是三态：字段缺失=不动；显式 null=清空；给值=写入。
 *  前端用 `JSON.stringify` 时 `undefined` 字段被 drop（缺失），`null` 显式
 *  序列化（→ `Some(None)`），有值（→ `Some(Some(value))`）。
 */
export type UpdateMobileSyncSettingsArgs = UpdateMobileSyncSettingsArgs_Serialize | UpdateMobileSyncSettingsArgs_Deserialize;

/**
 *  `update_mobile_sync_settings` 入参 patch。
 * 
 *  `lanAdvertiseIp` / `lanPort` 是三态：字段缺失=不动；显式 null=清空；给值=写入。
 *  前端用 `JSON.stringify` 时 `undefined` 字段被 drop（缺失），`null` 显式
 *  序列化（→ `Some(None)`），有值（→ `Some(Some(value))`）。
 */
export type UpdateMobileSyncSettingsArgs_Deserialize = {
	enabled?: boolean | null,
	lanListenEnabled?: boolean | null,
	lanAdvertiseIp?: string | null,
	lanPort?: number | null,
};

/**
 *  `update_mobile_sync_settings` 入参 patch。
 * 
 *  `lanAdvertiseIp` / `lanPort` 是三态：字段缺失=不动；显式 null=清空；给值=写入。
 *  前端用 `JSON.stringify` 时 `undefined` 字段被 drop（缺失），`null` 显式
 *  序列化（→ `Some(None)`），有值（→ `Some(Some(value))`）。
 */
export type UpdateMobileSyncSettingsArgs_Serialize = {
	enabled: boolean | null,
	lanListenEnabled: boolean | null,
	lanAdvertiseIp: string | null,
	lanPort: number | null,
};

export type UpdateMobileSyncSettingsResult = {
	enabled: boolean,
	lanListenEnabled: boolean,
	lanAdvertiseIp: string | null,
	lanPort: number | null,
	/**
	 *  Wire-兼容历史字段。daemon 装入 LAN lifecycle controller 时
	 *  (GUI 路径) settings 改动即时生效, 本字段永远为 false; CLI fallback
	 *  装配仍按"任一字段实际变化 → true / 同值 → false"返回, 表达
	 *  "下一次 daemon 重启才生效"的旧语义。前端按本字段决定是否弹
	 *  restart 横幅, true → 弹, false → 即时反馈即可。
	 */
	restartRequired: boolean,
	/**
	 *  即时生效路径下 LAN listener bind 失败的原因。
	 * 
	 *  写盘成功但 adapter `apply(target)` 后端口没起来时(端口占用、权限
	 *  不足、IP 不可分配等),facade 从 `MobileSyncEndpointInfoPort` 读出
	 *  `BindFailed{reason}` 并透传到此字段。前端引导对话框据此在 happy
	 *  path 流程中提前 toast.error 并阻断下一步, 避免用户填完 label 才
	 *  发现 iPhone 连不上。CLI fallback / 无 lifecycle 装配下永远为 None。
	 */
	lanListenerBindError: string | null,
};

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent = UpdateUiEvent_Serialize | UpdateUiEvent_Deserialize;

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent_Deserialize = 
/**  用户打开了 `UpdateDialog` / `PackageManagerUpdateDialog`。 */
({ kind: "dialog_opened"; source: UiDialogOpenSource; phase: UiUpdatePhase }) & { action?: never; error_kind?: never; outcome?: never } | 
/**  用户放弃了对话框（稍后 / 关闭 / 取消）。 */
({ kind: "dismissed"; phase: UiUpdatePhase; source: UiDismissSource }) & { action?: never; error_kind?: never; outcome?: never } | 
/**
 *  前端纯 UI 路径触发的 action（如 `Cancelled`）。
 * 
 *  `error_kind` 必须是短标识符（< 32 字符，形如 `user_cancelled`）；
 *  **绝不** 含路径 / URL / IP 等可还原用户标识的内容（schema doc §6.1）。
 */
({ kind: "action_invoked"; action: UiUpdateAction; outcome: UiUpdateActionOutcome; error_kind?: string | null }) & { phase?: never; source?: never };

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent_Serialize = 
/**  用户打开了 `UpdateDialog` / `PackageManagerUpdateDialog`。 */
({ kind: "dialog_opened"; source: UiDialogOpenSource; phase: UiUpdatePhase }) & { action?: never; error_kind?: never; outcome?: never } | 
/**  用户放弃了对话框（稍后 / 关闭 / 取消）。 */
({ kind: "dismissed"; phase: UiUpdatePhase; source: UiDismissSource }) & { action?: never; error_kind?: never; outcome?: never } | 
/**
 *  前端纯 UI 路径触发的 action（如 `Cancelled`）。
 * 
 *  `error_kind` 必须是短标识符（< 32 字符，形如 `user_cancelled`）；
 *  **绝不** 含路径 / URL / IP 等可还原用户标识的内容（schema doc §6.1）。
 */
({ kind: "action_invoked"; action: UiUpdateAction; outcome: UiUpdateActionOutcome; error_kind?: string | null }) & { phase?: never; source?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}
