// @ts-nocheck
/* eslint-disable */
// prettier-ignore
//
// AUTO-GENERATED by `cargo test -p uc-tauri --test specta_export`. DO NOT EDIT.
//
// 任何 #[tauri::command] / DTO / error enum 的形状变更都要重新跑这个测试
// 同步该文件，否则 CI 的 schema drift check 会拒绝合并。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Update tray menu labels to match the UI language.
	 * 
	 *  This is a UI sync command only; it does not persist settings.
	 */
	setTrayLanguage: (language: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_tray_language", { language, trace })),
	/**
	 *  Get the OS process ID of the Tauri application.
	 * 
	 *  获取 Tauri 应用的操作系统进程 ID。
	 */
	getTauriPid: () => __TAURI_INVOKE<number>("get_tauri_pid"),
	/**  Get the stable local device identifier used for telemetry correlation. */
	getDeviceId: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<string, CommandError>(__TAURI_INVOKE("get_device_id", { trace })),
	/**
	 *  Returns the full device + app meta to the webview.
	 * 
	 *  该命令是 PR1 跨设备可观测性改造的一部分:webview 启动后通过它一次性把
	 *  Sentry initialScope 补齐,让前后端事件在 Sentry 上能用同一组 tag(尤其是
	 *  `device.id`)互相关联。底层数据来自启动期一次性 resolve 的 [`uc_observability::ScopeContext`]。
	 */
	getDeviceMeta: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<DeviceMeta, CommandError>(__TAURI_INVOKE("get_device_meta", { trace })),
	/**
	 *  Read the daemon connection info from managed state.
	 * 
	 *  Pure status read from managed state; no usecase orchestration is required.
	 */
	getDaemonConnectionInfo: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	baseUrl: string,
	wsUrl: string,
} | null, CommandError>(__TAURI_INVOKE("get_daemon_connection_info", { trace })),
	/**
	 *  Exchange daemon bearer credentials for a short-lived webview session.
	 * 
	 *  The raw bearer token stays in the native Tauri side; the webview only receives
	 *  the daemon's session JWT and its refresh metadata.
	 */
	getDaemonSession: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	sessionToken: string,
	expiresInSecs: number,
	refreshAtSecs: number,
} | null, CommandError>(__TAURI_INVOKE("get_daemon_session", { trace })),
	/**
	 *  Restarts the running Tauri application to apply settings changes.
	 * 
	 *  流程:
	 *  1. emit `app://shutting-down` → 前端 disconnect WebSocket
	 *  2. wait `SHUTDOWN_FRONTEND_GRACE_MS` 让 WS close frame 飞过 loopback
	 *  3. graceful shutdown owned daemon (释放 HTTP / LAN 端口),最长
	 *     [`DAEMON_SHUTDOWN_TIMEOUT`] 兜底
	 *  4. `app.restart()` —— Tauri spawn 新进程 + exit 当前进程
	 * 
	 *  不走 Tauri 的 `RunEvent::ExitRequested` 路径 —— `app.restart()` 是 raw
	 *  exit,不触发 RunEvent。所以这里**必须**自己重做一次 graceful shutdown,
	 *  否则新进程启动时旧 daemon 还在持端口 → bind 失败 → daemon 起不来。
	 * 
	 *  用户的"需要重启"设置(LAN-only Mode / mobile_sync 端口等)都走这条
	 *  路径。iroh `IrohNodeBuilder::bind` 是进程级单次约束(Pitfall 3),
	 *  任何涉及 iroh_config 变更的 settings 必须新进程重新 bind,所以
	 *  `app.restart()` 是合适的、唯一的入口。
	 */
	restartApp: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("restart_app", { trace })),
	/**
	 *  Update the "launch at login" preference and apply it to the OS.
	 * 
	 *  Persists `auto_start` through the settings facade first (the stored
	 *  preference is the source of truth), then reconciles the OS-level launch
	 *  registration via [`AutostartPort`]. If the OS step fails, the persisted
	 *  setting is rolled back so settings never claim a state the OS rejected.
	 * 
	 *  更新开机自启动偏好并应用到操作系统：先经设置 facade 持久化（存储偏好为
	 *  真相源），再通过 [`AutostartPort`] 对齐 OS 启动项；OS 步骤失败时回滚已
	 *  持久化的设置，避免设置声称一个 OS 未能达成的状态。
	 */
	updateAutostart: (enabled: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_autostart", { enabled, trace })),
	/**
	 *  Tauri command — thin shell over [`do_check_for_update`] that emits
	 *  `update_check_performed { source: "manual", ... }` after the inner
	 *  resolves. scheduler-driven checks emit the same event with a different
	 *  `source`（schema doc §7.8）；inner 函数本身不 emit。
	 */
	checkForUpdate: (channel: string | null, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<{
	version: string,
	currentVersion: string,
	body: string | null,
	date: string | null,
} | null, string>(__TAURI_INVOKE("check_for_update", { channel, trace })),
	/**
	 *  Download the pending update in the background, broadcasting progress
	 *  via `UPDATE_PROGRESS_EVENT`. Awaitable: the future resolves when the
	 *  download completes, fails, or is cancelled.
	 * 
	 *  Thin shell over [`do_download_update`] that emits
	 *  `update_action_invoked { action = "download_bg", outcome = started }`
	 *  at entry (once the action actually transitions to `Downloading`) and
	 *  a terminal `Succeeded` / `Failed` / `Cancelled` after the inner
	 *  returns. Precondition rejections are returned to the frontend without
	 *  emitting any telemetry —— the user did not actually start a download,
	 *  so we keep the funnel分母干净.
	 * 
	 *  Pre-condition: state must be `Available`. `Downloading` returns
	 *  "already downloading"; `Ready` returns "already downloaded"; `None`
	 *  returns "no pending update".
	 */
	downloadUpdate: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("download_update", { trace })),
	/**
	 *  Signal an in-flight `download_update` to abort. No-op if the state is
	 *  not `Downloading`. The download future is dropped by the `tokio::select!`
	 *  in `download_update`, which terminates the underlying HTTP stream.
	 */
	cancelDownload: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { trace })),
	/**
	 *  Return the current download state so a freshly-mounted frontend listener
	 *  can sync up before attaching to `UPDATE_PROGRESS_EVENT`.
	 */
	getDownloadProgress: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<DownloadProgressSnapshot, string>(__TAURI_INVOKE("get_download_progress", { trace })),
	/**
	 *  Install the pending update.
	 * 
	 *  - `Ready`: install cached bytes via `Update::install`, then restart.
	 *    On failure, restore the `Ready` state so the user can retry.
	 *  - `Available`: legacy combined download+install path via
	 *    `Update::download_and_install`, with progress on the per-invocation
	 *    `Channel<DownloadEvent>` for compatibility with the existing dialog.
	 *  - `Downloading`: refuse (caller should wait or cancel first).
	 *  - `None`: refuse.
	 */
	installUpdate: (onEvent: Channel<DownloadEvent>, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("install_update", { onEvent, trace })),
	/**
	 *  Detect how the current binary was installed.
	 * 
	 *  Cached after the first call. On Linux the detection asks dpkg/rpm whether
	 *  `current_exe()` is in their package DB — that way users on a mixed system
	 *  (e.g. apt + rpm side-by-side) get the right answer rather than a guess
	 *  based on `/etc/*-release`.
	 */
	getInstallKind: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<InstallKind, string>(__TAURI_INVOKE("get_install_kind", { trace })),
	/**
	 *  Dev-only: manually open the Sparkle-style updater window with mock data.
	 * 
	 *  Wired to a debug-build button in `AboutSection.tsx` so we can iterate on
	 *  the window's UI without waiting for a real update to be detected. Release
	 *  builds short-circuit with an error so the command can't be misused —
	 *  `#[cfg]` is intentionally on the body, not the signature, to keep the
	 *  specta-generated TS surface stable across build profiles.
	 */
	devOpenUpdaterWindow: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("dev_open_updater_window", { trace })),
	/**
	 *  把前端 UI 触发的 update lifecycle 事件回送到后端 PostHog facade。
	 * 
	 *  仅 `DialogOpened` 会触发 `install_kind` probe；其他 variant 走直通映射。
	 *  `analytics::capture` 自身是 fire-and-forget，所以本 command 不返回 wire 错误
	 *  （即使 sink 在异步路径上失败，前端也无可处置；同 `commands/updater.rs`
	 *  内部 emission 一致）。
	 */
	captureUpdateUiEvent: (event: UpdateUiEvent_Deserialize, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("capture_update_ui_event", { event, trace })),
	/**
	 *  Open the application data directory in the system file manager.
	 *  在系统文件管理器中打开应用数据目录。
	 */
	openDataDirectory: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("open_data_directory", { trace })),
	/**
	 *  Open the application logs directory in the system file manager.
	 *  在系统文件管理器中打开应用日志目录。
	 */
	openLogsDirectory: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("open_logs_directory", { trace })),
	/**
	 *  Hide the quick panel, re-activate the previous app, and paste.
	 * 
	 *  隐藏快捷面板，重新激活之前的应用，并粘贴。
	 */
	pasteToPreviousApp: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("paste_to_previous_app", { trace })),
	/**
	 *  Dismiss the quick panel and return focus to the previous app (no paste).
	 * 
	 *  关闭快捷面板并将焦点返回到之前的应用（不粘贴）。
	 */
	dismissQuickPanel: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("dismiss_quick_panel", { trace })),
	/**  Update quick panel size and centered position from the active UI scale. */
	setQuickPanelLayout: (scale: number | null, previewExpanded: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_quick_panel_layout", { scale, previewExpanded, trace })),
	/**
	 *  Finalize the quick panel show after the frontend has cleared stale state.
	 * 
	 *  前端清理完旧状态后，实际显示快捷面板窗口。
	 */
	finalizeQuickPanelShow: (trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("finalize_quick_panel_show", { trace })),
	/**
	 *  实时启用/禁用快捷面板。
	 * 
	 *  与 `update_keyboard_shortcuts` 走同一把 [`KeyboardShortcutsUpdateLock`],
	 *  因为两者都会改 OS 全局快捷键的注册状态——并发执行会让 OS 状态、
	 *  [`CurrentShortcuts`] 内存视图、和 facade 持久化值互相错位。
	 * 
	 *  流程:
	 *    1. 拿锁,读当前 settings。
	 *    2. 与 `enabled` 比较:无变化直接返回。
	 *    3. 计算 desired OS 快捷键列表(开启时 = `resolve_quick_panel_shortcuts`,
	 *       关闭时 = `[]`)。
	 *    4. 在 main thread 上一次性完成:开启 → `pre_create` + `register`,
	 *       关闭 → 只 `unregister`,**不**销毁面板窗口。`tauri-plugin-global-shortcut`
	 *       与 webview 创建都要求 main thread。
	 *    5. 调 facade 持久化 patch。失败时反向回滚 OS 副作用,避免出现
	 *       "OS 已生效但磁盘没存"或反过来的撕裂状态。
	 *    6. 成功后 `shortcut_registry.replace(...)`,让后续 `update_keyboard_shortcuts`
	 *       能算对 old/new diff。
	 * 
	 *  **关闭路径不彻底释放 webview**:macOS 上销毁 NSPanel 会与 ObjC 类替换 +
	 *  on_window_event 异步任务发生 race 而崩溃。所以关闭只反注册 OS 快捷键,
	 *  隐藏的 WKWebView / WebContent XPC 进程依旧存在,UI 会提示用户重启 GUI
	 *  才能完全释放资源。下次启动期 `quick_panel.enabled = false` 会跳过
	 *  `pre_create`,自然不会再有这些进程。
	 */
	setQuickPanelEnabled: (enabled: boolean, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_quick_panel_enabled", { enabled, trace })),
	/**  保存键盘快捷键，并同步快捷面板全局快捷键的 OS 注册状态。 */
	updateKeyboardShortcuts: (shortcuts: { [key in string]: ShortcutKeyDto | null }, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<UpdateKeyboardShortcutsResult, CommandError>(__TAURI_INVOKE("update_keyboard_shortcuts", { shortcuts, trace })),
	/**
	 *  对单个候选中继 URL 发起一次握手探测。
	 * 
	 *  不读取也不修改任何持久化设置;UI 可以重复调用以做"在保存前先试一下"。
	 *  探测失败映射到 [`RelayProbeOutcome`] 的细分变体,系统级故障(adapter
	 *  未装配等)走 [`CommandError`]。
	 */
	probeRelayUrl: (url: string, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<RelayProbeOutcome, CommandError>(__TAURI_INVOKE("probe_relay_url", { url, trace })),
	/**
	 *  调整 macOS 主窗口三色交通灯（close/min/zoom）按钮位置。
	 * 
	 *  `offset_x` / `offset_y` 相对系统给的标准位置偏移，**屏幕坐标系**：
	 *  正 X 向右、正 Y 向下。调用幂等。非 macOS 平台 no-op。
	 */
	setTrafficLightPosition: (offsetX: number | null, offsetY: number | null, trace: {
	trace_id: string,
	timestamp: number,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_traffic_light_position", { offsetX, offsetY, trace })),
};

/** Events */
export const events = {
	clipboardDeliveryStatusChanged: makeEvent<ClipboardDeliveryStatusChanged>("clipboard-delivery-status-changed"),
};

/* Types */
/**
 *  `clipboard_delivery_status_changed` 事件 payload。
 * 
 *  前端 detail 视图按 `entry_id` 过滤后 refetch `GET /clipboard/entries/{id}/delivery`
 *  (ADR-008 P3-1 起走 daemon loopback API),拿 view 内的 status 渲染。
 *  `target_device_id` 当前未被消费,留作未来 per-peer 局部刷新的钩子。
 */
export type ClipboardDeliveryStatusChanged = {
	/**
	 *  触发本次变更的 entry id。前端 detail 视图按当前打开的 entry_id 过滤,
	 *  只对匹配事件 refetch。
	 */
	entryId: string,
	/**  投递目标对端。view 渲染时按对端聚合状态,事件粒度也是按对端。 */
	targetDeviceId: string,
};

/**
 *  Typed command error taxonomy for Tauri command boundary.
 * 
 *  Serializes to {"code": "...", "message": "..."} for frontend discriminated union handling.
 */
export type CommandError = { code: "NotFound"; message: string } | { code: "InternalError"; message: string } | { code: "Timeout"; message: string } | { code: "Cancelled"; message: string } | { code: "ValidationError"; message: string } | { code: "Conflict"; message: string };

export type DaemonConnectionPayload = {
	baseUrl: string,
	wsUrl: string,
};

export type DaemonSessionPayload = {
	sessionToken: string,
	expiresInSecs: number,
	refreshAtSecs: number,
};

/**
 *  暴露给 webview 的设备和应用元数据，用于补齐前端 Sentry scope。
 * 
 *  字段命名与后端 `ScopeContext` 一一对应（`device.id` / `device.role` /
 *  `device.platform` / `app.version` / `app.channel`）。webview 侧的
 *  `device.role` 默认仍是 `webview`，这里返回的 `device_role` 是 *Rust 主进程*
 *  的角色（`gui-host`），webview 把它打到 `device.host_role` 二级 tag 上,
 *  便于 Sentry 上同时看到两端。
 */
export type DeviceMeta = {
	deviceId: string,
	deviceRole: string,
	platform: string,
	appVersion: string,
	appChannel: string,
};

/**
 *  Events emitted during update download.
 * 
 *  Carried both via the broadcast `UPDATE_PROGRESS_EVENT` (background
 *  download) and via the per-invocation `Channel<DownloadEvent>` passed to
 *  `install_update` (legacy combined download+install path).
 */
export type DownloadEvent = { event: "Started"; data: {
	contentLength: number | null,
} } | { event: "Progress"; data: {
	chunkLength: number,
} } | { event: "Finished" } | { event: "Failed"; data: {
	error: string,
} };

/**
 *  Coarse-grained phase used by `get_download_progress` so a frontend that
 *  mounts mid-download can render the right icon variant.
 */
export type DownloadPhase = "idle" | "available" | "downloading" | "ready";

/**
 *  Snapshot of current download state, queryable from the frontend so a
 *  just-mounted listener can sync up before attaching to the event stream.
 */
export type DownloadProgressSnapshot = {
	phase: DownloadPhase,
	downloaded: number,
	total: number | null,
	/**  Newly-available (latest) version. `None` when phase is `Idle`. */
	version: string | null,
	/**
	 *  Currently-installed app version, lifted directly from
	 *  `app.package_info().version`. Always populated even when phase is
	 *  `Idle`, so a mid-mount frontend can render "current vs. latest"
	 *  without waiting for a fresh `check_for_update` round-trip.
	 */
	currentVersion: string,
	/**
	 *  Release notes for the available version, if any. `None` when phase
	 *  is `Idle` or the release ships no notes.
	 */
	body: string | null,
	/**
	 *  Release date for the available version, if any. `None` when phase
	 *  is `Idle`.
	 */
	date: string | null,
};

/**
 *  Installation provenance of the running binary.
 * 
 *  Used by the frontend to short-circuit in-app update when the user is on a
 *  system-packaged Linux build: Tauri's Linux updater only supports
 *  AppImage, so deb/rpm users must be routed to their package manager.
 */
export type InstallKind = "macos" | "windows" | 
/**
 *  Windows portable ("green") zip. The in-app updater would try to run the
 *  NSIS installer, which installs into Program Files rather than updating
 *  the portable folder — so the frontend routes this kind to a
 *  "download the new portable zip" dialog instead of self-installing.
 */
"windowsportable" | "appimage" | "deb" | "rpm" | "unknown";

/**
 *  一次 `probe_relay_url` 调用的细分结果。
 * 
 *  探测失败属于"用户可以理解的预期场景"(URL 写错、对端 DNS 不可达、TLS
 *  不可信等),所以这些状态以 `Ok(outcome)` 的形式返回,让前端可以在不抛
 *  异常的前提下区分文案。系统级故障(facade 缺失装配、trace 解析失败等)
 *  仍然走 [`CommandError`]。
 */
export type RelayProbeOutcome = { kind: "success"; latencyMs: number } | { kind: "invalidUrl"; message: string } | { kind: "dns"; message: string } | { kind: "tls"; message: string } | { kind: "handshake"; message: string } | { kind: "timeout" } | { kind: "other"; message: string };

export type ShortcutKeyDto = string | string[];

export type TraceMetadata = {
	trace_id: string,
	timestamp: number,
};

/**  见 [`analytics::DialogOpenSource`]。wire form: `notification` | `sidebar_icon`。 */
export type UiDialogOpenSource = "notification" | "sidebar_icon";

/**
 *  见 [`analytics::DismissSource`]。wire form: `dialog_later` | `dialog_closed` |
 *  `package_manager_dialog_closed`。
 */
export type UiDismissSource = "dialog_later" | "dialog_closed" | "package_manager_dialog_closed";

/**  见 [`analytics::UpdateAction`]。wire form: `download_bg` | `install`。 */
export type UiUpdateAction = "download_bg" | "install";

/**
 *  见 [`analytics::UpdateActionOutcome`]。wire form: `started` | `succeeded` |
 *  `failed` | `cancelled`。
 */
export type UiUpdateActionOutcome = "started" | "succeeded" | "failed" | "cancelled";

/**  见 [`analytics::UpdatePhase`]。wire form: `available` | `downloading` | `ready`。 */
export type UiUpdatePhase = "available" | "downloading" | "ready";

export type UpdateKeyboardShortcutsResult = {
	keyboardShortcuts: { [key in string]: ShortcutKeyDto },
};

/**  Metadata returned to the frontend when an update is available. */
export type UpdateMetadata = {
	version: string,
	currentVersion: string,
	body: string | null,
	date: string | null,
};

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent = UpdateUiEvent_Serialize | UpdateUiEvent_Deserialize;

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent_Deserialize = 
/**  用户打开了 `UpdateDialog` / `PackageManagerUpdateDialog`。 */
({ kind: "dialog_opened"; source: UiDialogOpenSource; phase: UiUpdatePhase }) & { action?: never; error_kind?: never; outcome?: never } | 
/**  用户放弃了对话框（稍后 / 关闭 / 取消）。 */
({ kind: "dismissed"; phase: UiUpdatePhase; source: UiDismissSource }) & { action?: never; error_kind?: never; outcome?: never } | 
/**
 *  前端纯 UI 路径触发的 action（如 `Cancelled`）。
 * 
 *  `error_kind` 必须是短标识符（< 32 字符，形如 `user_cancelled`）；
 *  **绝不** 含路径 / URL / IP 等可还原用户标识的内容（schema doc §6.1）。
 */
({ kind: "action_invoked"; action: UiUpdateAction; outcome: UiUpdateActionOutcome; error_kind?: string | null }) & { phase?: never; source?: never };

/**
 *  前端送来的 UI 触发事件（discriminated union by `kind`）。
 * 
 *  `install_kind` 不出现在任何 variant 里 —— 由后端在 dispatch 时反查注入
 *  （schema doc §7.8 落地备注）。
 */
export type UpdateUiEvent_Serialize = 
/**  用户打开了 `UpdateDialog` / `PackageManagerUpdateDialog`。 */
({ kind: "dialog_opened"; source: UiDialogOpenSource; phase: UiUpdatePhase }) & { action?: never; error_kind?: never; outcome?: never } | 
/**  用户放弃了对话框（稍后 / 关闭 / 取消）。 */
({ kind: "dismissed"; phase: UiUpdatePhase; source: UiDismissSource }) & { action?: never; error_kind?: never; outcome?: never } | 
/**
 *  前端纯 UI 路径触发的 action（如 `Cancelled`）。
 * 
 *  `error_kind` 必须是短标识符（< 32 字符，形如 `user_cancelled`）；
 *  **绝不** 含路径 / URL / IP 等可还原用户标识的内容（schema doc §6.1）。
 */
({ kind: "action_invoked"; action: UiUpdateAction; outcome: UiUpdateActionOutcome; error_kind?: string | null }) & { phase?: never; source?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

