import { redactSensitiveArgs } from '@/observability/redaction'
import { Sentry, sentryEnabled } from '@/observability/sentry'

/**
 * Wrap a Rust-side typed-error envelope (`{ code: string, ...payload }`) into
 * a real `Error` so Sentry can derive a message and group issues by
 * command × code. Pre-existing `Error` instances and non-envelope rejections
 * pass through unchanged.
 *
 * Why: Tauri commands generated by tauri-specta reject with the typed-error
 * union verbatim — a plain object with no prototype Sentry recognises. Passed
 * to `captureException`, every such rejection collapses into one issue titled
 * `"Object captured as exception with keys: <...>"` with no actionable info.
 * The original payload is preserved on `cause` (redacted) so the Sentry UI
 * still shows the variant fields.
 */
export function toReportableError(error: unknown, command: string): unknown {
  if (error instanceof Error) return error
  if (typeof error === 'object' && error !== null && 'code' in error) {
    const code = String((error as { code: unknown }).code)
    const wrapped = new Error(`Tauri command "${command}" failed: ${code}`)
    wrapped.name = `TauriCommandError(${code})`
    ;(wrapped as Error & { cause?: unknown }).cause = redactSensitiveArgs(error)
    return wrapped
  }
  return error
}

export class RecoverableError extends Error {
  constructor(
    message: string,
    public context: Record<string, unknown> = {}
  ) {
    super(message)
  }
}

export class CriticalError extends Error {
  constructor(
    message: string,
    public context: Record<string, unknown> = {}
  ) {
    super(message)
  }
}

export class ExpectedError extends Error {}

export function reportError(error: unknown, context?: Record<string, unknown>) {
  if (!sentryEnabled || error instanceof ExpectedError) {
    return
  }
  Sentry.captureException(error, { extra: context })
}
