import { USER_FACING_ERROR_CODES } from '@/lib/error-severity.generated'
import { redactSensitiveArgs } from '@/observability/redaction'
import { Sentry, sentryEnabled } from '@/observability/sentry'

/**
 * Wrap a Rust-side typed-error envelope (`{ code: string, ...payload }`) into
 * a real `Error` so Sentry can derive a message and group issues by
 * command × code. Pre-existing `Error` instances and non-envelope rejections
 * pass through unchanged.
 *
 * Why: Tauri commands generated by tauri-specta reject with the typed-error
 * union verbatim — a plain object with no prototype Sentry recognises. Passed
 * to `captureException`, every such rejection collapses into one issue titled
 * `"Object captured as exception with keys: <...>"` with no actionable info.
 * The original payload is preserved on `cause` (redacted) so the Sentry UI
 * still shows the variant fields.
 */
export function toReportableError(error: unknown, command: string): unknown {
  if (error instanceof Error) return error
  if (typeof error === 'object' && error !== null && 'code' in error) {
    const code = String((error as { code: unknown }).code)
    const wrapped = new Error(`Tauri command "${command}" failed: ${code}`)
    wrapped.name = `TauriCommandError(${code})`
    ;(wrapped as Error & { cause?: unknown }).cause = redactSensitiveArgs(error)
    return wrapped
  }
  return error
}

/**
 * Whether a Tauri command rejection is an *expected* user/validation error —
 * the user typed a bad username, entered the wrong passphrase, picked a name
 * already taken, etc. These are normal product flow: the UI shows a message and
 * the user retries. They MUST NOT be reported to Sentry, or real system-error
 * alerts drown in input-validation noise.
 *
 * The taxonomy is owned by the Rust side (`commands/severity.rs`) and exported
 * to `USER_FACING_ERROR_CODES`; an unrecognized `code` (or a non-envelope
 * rejection) is treated as a *system* error and reported — failing safe toward
 * visibility rather than silently swallowing an unexpected failure.
 */
export function isExpectedCommandError(error: unknown): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    typeof (error as { code: unknown }).code === 'string' &&
    USER_FACING_ERROR_CODES.has((error as { code: string }).code)
  )
}

class ExpectedError extends Error {}

export function reportError(error: unknown, context?: Record<string, unknown>) {
  if (!sentryEnabled || error instanceof ExpectedError || isExpectedCommandError(error)) {
    return
  }
  Sentry.captureException(error, { extra: context })
}
