//! IPC binding 文件 codegen + schema drift 闸门。
//!
//! ## 为什么把 codegen 放在 cargo test 里
//!
//! tauri-specta 官方 example 把 `builder.export(...)` 放在 `main.rs`
//! 的 `#[cfg(debug_assertions)]` 里。我们项目用 workspace lib crate
//! (`uc-tauri`)，没有 main 入口；放到 dev-test target 有三个好处：
//! 1. 命令清单变更后任何人 `cargo test --workspace` 都会立刻刷新 binding；
//! 2. CI 跑这个 test → `git diff --exit-code src/lib/ipc-bindings.generated.ts`
//!    就是天然的 schema drift 闸门；
//! 3. 不污染 release binary（test target 不进 prod 链路）。
//!
//! 失败模式：commands/DTO 字段改了但 binding 没刷新 → CI diff 红 →
//! 提示开发者本地跑一次 `cargo test -p uc-tauri --test specta_export`
//! 后再次提交。

use std::path::PathBuf;

use specta_typescript::Typescript;

/// 从 `src-tauri/crates/uc-tauri/` 走到 repo 根的 `src/lib/ipc-bindings.generated.ts`。
/// `CARGO_MANIFEST_DIR` 在 compile 时被替换成绝对路径，避免被 cwd 影响。
const BINDINGS_PATH_FROM_CRATE: &str = "../../../src/lib/ipc-bindings.generated.ts";

/// codegen header —— 写在生成文件最顶部。
///
/// - `@ts-nocheck` + eslint-disable: 生成文件绕开仓库 lint 规则；
/// - `prettier-ignore`: 配合 `.prettierignore` 双保险；
/// - banner 提示开发者这是 generated artifact，改源不是改这里。
const HEADER: &str = "// @ts-nocheck\n\
/* eslint-disable */\n\
// prettier-ignore\n\
//\n\
// AUTO-GENERATED by `cargo test -p uc-tauri --test specta_export`. DO NOT EDIT.\n\
//\n\
// 任何 #[tauri::command] / DTO / error enum 的形状变更都要重新跑这个测试\n\
// 同步该文件，否则 CI 的 schema drift check 会拒绝合并。\n";

#[test]
fn export_ipc_bindings() {
    let target: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(BINDINGS_PATH_FROM_CRATE);

    // BigInt 行为：specta-typescript 0.0.12 默认对 `u64/i64/i128` 走 `bigint`
    // 字面量（前端拿到 `bigint` 类型）。本仓库 wire 上的 `*_at_ms` 时间戳与
    // `chunk_length` / `downloaded` / `total` 等字段全部落在 `Number.MAX_SAFE_INTEGER`
    // 内，前端历史代码全部按 `number` 处理；如果生成的 binding 把它们打成
    // `bigint`，前端 `JSON.stringify` 链路会撞 `TypeError`。后续如有真正超过
    // 2^53 的字段，应在 DTO 上加 `#[specta(type = "string")]` 显式转字符串
    // 而不是把全局策略改回 bigint。
    let exporter = Typescript::default().header(HEADER);

    uc_tauri::specta_builder::build()
        .export(exporter, &target)
        .unwrap_or_else(|e| panic!("specta export to {} failed: {e}", target.display()));
}
