import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { bumpVersion, parseSemver } from '../bump-version-lib.js'
import { updateCargoLock, updateCargoToml } from '../bump-version.js'

describe('workspace version inheritance', () => {
  it('uc-cli uses version.workspace = true', () => {
    const content = fs.readFileSync(path.resolve(__dirname, '../../apps/cli/Cargo.toml'), 'utf8')
    expect(content).toContain('version.workspace = true')
    expect(content).not.toMatch(/^version\s*=\s*"[\d.]+"/m)
  })
})

describe('bumpVersion prerelease patch', () => {
  it('keeps base version when creating first alpha prerelease', () => {
    expect(bumpVersion('0.1.0', 'patch', 'alpha')).toBe('0.1.0-alpha.1')
  })

  it('increments alpha prerelease number on repeat', () => {
    expect(bumpVersion('0.1.0-alpha.1', 'patch', 'alpha')).toBe('0.1.0-alpha.2')
  })
})

describe('parseSemver target version', () => {
  it('accepts explicit prerelease target version', () => {
    const parsed = parseSemver('0.1.0-alpha.2')
    expect(parsed.prerelease).toBe('alpha')
    expect(parsed.prereleaseVersion).toBe(2)
  })
})

describe('updateCargoToml', () => {
  const tempDirs: string[] = []

  afterEach(() => {
    while (tempDirs.length > 0) {
      const dir = tempDirs.pop()
      if (dir) {
        fs.rmSync(dir, { recursive: true, force: true })
      }
    }
  })

  it('updates only the package version and preserves dependency versions', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    const manifestPath = path.join(repoDir, 'Cargo.toml')
    fs.writeFileSync(
      manifestPath,
      '[package]\nname = "uniclipboard"\nversion = "0.20.0-alpha.5"\n\n[dependencies.tauri-plugin-wdio]\nversion = "1"\noptional = true\n\n[dependencies.tauri-plugin-wdio-webdriver]\nversion = "1"\noptional = true\n',
      'utf8'
    )

    updateCargoToml('0.20.0-alpha.6', false, path.relative(process.cwd(), manifestPath))

    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(
      '[package]\nname = "uniclipboard"\nversion = "0.20.0-alpha.6"\n\n[dependencies.tauri-plugin-wdio]\nversion = "1"\noptional = true\n\n[dependencies.tauri-plugin-wdio-webdriver]\nversion = "1"\noptional = true\n'
    )
  })

  it('updates only the workspace package version', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    const manifestPath = path.join(repoDir, 'Cargo.toml')
    fs.writeFileSync(
      manifestPath,
      '[workspace.package]\nversion = "0.20.0-alpha.5"\n\n[dependencies.release-helper]\nversion = "2"\n',
      'utf8'
    )

    updateCargoToml(
      '0.20.0-alpha.6',
      false,
      path.relative(process.cwd(), manifestPath),
      'workspace.package'
    )

    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(
      '[workspace.package]\nversion = "0.20.0-alpha.6"\n\n[dependencies.release-helper]\nversion = "2"\n'
    )
  })
})

describe('updateCargoLock', () => {
  const tempDirs: string[] = []
  const originalCwd = process.cwd()

  afterEach(() => {
    process.chdir(originalCwd)
    while (tempDirs.length > 0) {
      const dir = tempDirs.pop()
      if (dir) {
        fs.rmSync(dir, { recursive: true, force: true })
      }
    }
  })

  it('updates the root package version in Cargo.lock', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'Cargo.lock'),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\ndependencies = []\n',
      'utf8'
    )

    const result = updateCargoLock('0.2.0-alpha.5', false)
    const updated = fs.readFileSync(path.join(repoDir, 'Cargo.lock'), 'utf8')

    expect(result.old).toBe('0.2.0-alpha.4')
    expect(result.new).toBe('0.2.0-alpha.5')
    expect(updated).toContain('name = "uniclipboard"\nversion = "0.2.0-alpha.5"')
  })

  it('does not write Cargo.lock during dry run', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    const lockPath = path.join(repoDir, 'Cargo.lock')
    const original =
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\ndependencies = []\n'
    fs.writeFileSync(lockPath, original, 'utf8')

    const result = updateCargoLock('0.2.0-alpha.5', true)
    const after = fs.readFileSync(lockPath, 'utf8')

    expect(result.old).toBe('0.2.0-alpha.4')
    expect(result.new).toBe('0.2.0-alpha.5')
    expect(after).toBe(original)
  })

  it('rewrites every workspace member that inherits the workspace version', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.mkdirSync(path.join(repoDir, 'crates', 'uc-core'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'crates', 'uc-core', 'Cargo.toml'),
      '[package]\nname = "uc-core"\nversion.workspace = true\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'Cargo.toml'),
      '[workspace]\nmembers = [\n  "crates/uc-core",\n  "src-tauri",\n]\n\n[workspace.package]\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'Cargo.lock'),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\ndependencies = []\n\n[[package]]\nname = "uc-core"\nversion = "0.2.0-alpha.4"\ndependencies = []\n',
      'utf8'
    )

    const result = updateCargoLock('0.2.0-alpha.5', false)
    const updated = fs.readFileSync(path.join(repoDir, 'Cargo.lock'), 'utf8')

    expect(result.old).toBe('0.2.0-alpha.4')
    expect(result.updated.map((entry) => entry.name).sort()).toEqual(['uc-core', 'uniclipboard'])
    expect(updated).toContain('name = "uniclipboard"\nversion = "0.2.0-alpha.5"')
    expect(updated).toContain('name = "uc-core"\nversion = "0.2.0-alpha.5"')
    expect(updated).not.toContain('0.2.0-alpha.4')
  })

  it('leaves lock entries alone when they already match the workspace version', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.mkdirSync(path.join(repoDir, 'crates', 'uc-core'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.5"\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'crates', 'uc-core', 'Cargo.toml'),
      '[package]\nname = "uc-core"\nversion.workspace = true\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'Cargo.toml'),
      '[workspace]\nmembers = [\n  "crates/uc-core",\n  "src-tauri",\n]\n\n[workspace.package]\nversion = "0.2.0-alpha.5"\n',
      'utf8'
    )
    const lockPath = path.join(repoDir, 'Cargo.lock')
    const original =
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.5"\ndependencies = []\n\n[[package]]\nname = "uc-core"\nversion = "0.2.0-alpha.5"\ndependencies = []\n'
    fs.writeFileSync(lockPath, original, 'utf8')

    const result = updateCargoLock('0.2.0-alpha.5', false)

    expect(result.updated).toEqual([])
    expect(fs.readFileSync(lockPath, 'utf8')).toBe(original)
  })
})
